config/routes.rb
Gallery::Application.routes.draw do
  resources :groups

  resources :arts

  resources :artists

end

app/models/art.rb
class Art < ActiveRecord::Base
end

app/models/artist.rb
class Artist < ActiveRecord::Base
end

app/models/artists.rb
class Artists < ActiveRecord::Base
end

app/models/group.rb
class Group < ActiveRecord::Base
end

app/models/works.rb
class Works < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  # GET /artists
  # GET /artists.json
  def index
    @artists = Artist.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @artists }
    end
  end

  # GET /artists/1
  # GET /artists/1.json
  def show
    @artist = Artist.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @artist }
    end
  end

  # GET /artists/new
  # GET /artists/new.json
  def new
    @artist = Artist.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @artist }
    end
  end

  # GET /artists/1/edit
  def edit
    @artist = Artist.find(params[:id])
  end

  # POST /artists
  # POST /artists.json
  def create
    @artist = Artist.new(params[:artist])

    respond_to do |format|
      if @artist.save
        format.html { redirect_to @artist, notice: 'Artist was successfully created.' }
        format.json { render json: @artist, status: :created, location: @artist }
      else
        format.html { render action: "new" }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /artists/1
  # PUT /artists/1.json
  def update
    @artist = Artist.find(params[:id])

    respond_to do |format|
      if @artist.update_attributes(params[:artist])
        format.html { redirect_to @artist, notice: 'Artist was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artists/1
  # DELETE /artists/1.json
  def destroy
    @artist = Artist.find(params[:id])
    @artist.destroy

    respond_to do |format|
      format.html { redirect_to artists_url }
      format.json { head :ok }
    end
  end
end

app/controllers/arts_controller.rb
class ArtsController < ApplicationController
  # GET /arts
  # GET /arts.json
  def index
    @arts = Art.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @arts }
    end
  end

  # GET /arts/1
  # GET /arts/1.json
  def show
    @art = Art.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @art }
    end
  end

  # GET /arts/new
  # GET /arts/new.json
  def new
    @art = Art.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @art }
    end
  end

  # GET /arts/1/edit
  def edit
    @art = Art.find(params[:id])
  end

  # POST /arts
  # POST /arts.json
  def create
    @art = Art.new(params[:art])

    respond_to do |format|
      if @art.save
        format.html { redirect_to @art, notice: 'Art was successfully created.' }
        format.json { render json: @art, status: :created, location: @art }
      else
        format.html { render action: "new" }
        format.json { render json: @art.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /arts/1
  # PUT /arts/1.json
  def update
    @art = Art.find(params[:id])

    respond_to do |format|
      if @art.update_attributes(params[:art])
        format.html { redirect_to @art, notice: 'Art was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @art.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /arts/1
  # DELETE /arts/1.json
  def destroy
    @art = Art.find(params[:id])
    @art.destroy

    respond_to do |format|
      format.html { redirect_to arts_url }
      format.json { head :ok }
    end
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @groups }
    end
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    @group = Group.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @group }
    end
  end

  # GET /groups/new
  # GET /groups/new.json
  def new
    @group = Group.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @group }
    end
  end

  # GET /groups/1/edit
  def edit
    @group = Group.find(params[:id])
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(params[:group])

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render json: @group, status: :created, location: @group }
      else
        format.html { render action: "new" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /groups/1
  # PUT /groups/1.json
  def update
    @group = Group.find(params[:id])

    respond_to do |format|
      if @group.update_attributes(params[:group])
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group = Group.find(params[:id])
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper_old.rb
module ArtistsHelper
  def full_name(artist)
    "#{artist.name_first}#{" #{artist.name_mi}." unless artist.name_mi.empty?} #{artist.name_last}"
  end
end

app/views/artists_old/_form.html.haml
= form_for @artist do |f|
  -if @artist.errors.any?
    #error_explanation
      %h2= "#{pluralize(@artist.errors.count, "error")} prohibited this artist from being saved:"
      %ul
        - @artist.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name_first
    = f.text_field :name_first
  .field
    = f.label :name_mi
    = f.text_field :name_mi
  .field
    = f.label :name_last
    = f.text_field :name_last
  .field
    = f.label :bio
    = f.text_area :bio
  .field
    = f.label :image_url
    = f.text_field :image_url
  .actions
    = f.submit 'Save'

app/views/artists_old/edit.html.haml
%h1 Editing artist

= render 'form'

= link_to 'Show', @artist
\|
= link_to 'Back', artists_path

app/views/artists_old/index.html.haml
%h1 artists

- @artists.each do |artist|
  - row_color = cycle('row_odd', 'row_even')
  %div{class: ["row_class", row_color]}
    .grid_1= image_tag(artist.image_url, class: 'list_image')
    .grid_9
      .list_name= full_name artist
      .list_bio= truncate(strip_tags(artist.bio), length: 220)
    .grid_1
      %br
      = link_to 'Show', artist 
      %br
      = link_to 'Edit', edit_artist_path(artist)
      %br
      = link_to 'Destroy', artist, :confirm => 'Are you sure?', :method => :delete


= link_to 'New Artist', new_artist_path

app/views/artists_old/new.html.haml
%h1 New artist

= render 'form'

= link_to 'Back', artists_path

app/views/artists_old/show.html.haml
%p#notice= notice

%table
  %tr
    %td= image_tag(@artist.image_url, class: "artist_image")
    %td
      .artist_name= full_name(@artist).downcase
      %br
      .artist_bio= strip_tags(@artist.bio)

= link_to 'Edit', edit_artist_path(@artist)
\|
= link_to 'Back', artists_path

app/views/arts_old/_form.html.haml
= form_for @art do |f|
  -if @art.errors.any?
    #error_explanation
      %h2= "#{pluralize(@art.errors.count, "error")} prohibited this art from being saved:"
      %ul
        - @art.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :medium
    = f.text_area :medium
  .field
    = f.label :image_url
    = f.text_field :image_url
  .field
    = f.label :created
    = f.date_select :created
  .field
    = f.label :artist_id
    = f.number_field :artist_id
  .actions
    = f.submit 'Save'

app/views/arts_old/edit.html.haml
%h1 Editing art

= render 'form'

= link_to 'Show', @art
\|
= link_to 'Back', arts_path

app/views/arts_old/index.html.haml
%h1 works

- @arts.each do |art|
  - row_color = cycle('row_odd', 'row_even')
  %div{class: ["row_class", row_color]}
    .grid_1= image_tag(art.image_url, class: 'list_image')
    .grid_9
      .list_name= art.name
      .list_desc= truncate(strip_tags(art.description), length: 220)
    .grid_1
      %br
      = link_to 'Show', art
      %br
      = link_to 'Edit', edit_art_path(art)
      %br
      = link_to 'Destroy', art, :confirm => 'Are you sure?', :method => :delete


= link_to 'New Art', new_art_path

app/views/arts_old/new.html.haml
%h1 New art

= render 'form'

= link_to 'Back', arts_path

app/views/arts_old/show.html.haml
/%p#notice= notice

.art_wrapper
  /.grid_4.alpha
  = image_tag(@art.image_url, class: "art_image")

.info_wrapper
  .info
    /.grid_5
    %p
      %b Name:
      = @art.name
    %p
      %b Artist:
      = @art.artist_id
    %p
      %b Description:
      = @art.description
    %p
      %b Medium:
      = @art.medium
    %p
      %b Created:
      = @art.created
    
.grid_12
  = link_to 'Edit', edit_art_path(@art)
  \|
  = link_to 'Back', arts_path

app/views/groups_old/_form.html.haml
= form_for @group do |f|
  -if @group.errors.any?
    #error_explanation
      %h2= "#{pluralize(@group.errors.count, "error")} prohibited this group from being saved:"
      %ul
        - @group.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :image_url
    = f.text_field :image_url
  .actions
    = f.submit 'Save'

app/views/groups_old/edit.html.haml
%h1 Editing group

= render 'form'

= link_to 'Show', @group
\|
= link_to 'Back', groups_path

app/views/groups_old/index.html.haml
%h1 Listing groups

%table
  %tr
    %th Name
    %th Description
    %th Image url
    %th
    %th
    %th

  - @groups.each do |group|
    %tr
      %td= group.name
      %td= group.description
      %td= group.image_url
      %td= link_to 'Show', group
      %td= link_to 'Edit', edit_group_path(group)
      %td= link_to 'Destroy', group, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Group', new_group_path

app/views/groups_old/new.html.haml
%h1 New group

= render 'form'

= link_to 'Back', groups_path

app/views/groups_old/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @group.name
%p
  %b Description:
  = @group.description
%p
  %b Image url:
  = @group.image_url

= link_to 'Edit', edit_group_path(@group)
\|
= link_to 'Back', groups_path

app/views/layouts/_title.html.haml
#title
  .name toelle hovan
  .menu &nbsp;classes
  .menu videos
  .menu events
  .menu works
  .menu.current home

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Gallery
    = stylesheet_link_tag     "application"
    = javascript_include_tag  "application"
    = csrf_meta_tags
  %body
    .container
      .grid_12= render "layouts/title"
    .container
      #content{class: [controller.controller_name]}= yield